### ISSUE TITLE
[Feature Request] Stepper Motor noises

### ISSUE THREAD

**Issue by thetrueyoshifan** [Codel1417/VRC-Ender-3#1]
With the default Ender 3, the stepper motors are actually pretty loud, giving the printer a distinct sound that I love. Would it be possible to have G0/G1 produce a scaled stepper motor sound when moving around the build plate? This could be toggleable, but I think it could be a super nice touch

**Comment by Codel1417** [comment]
![image](https://user-images.githubusercontent.com/13484789/121972012-f2c33080-cd2e-11eb-9ff5-9321897b46fb.png)
SOON (tm)

**Comment by Codel1417** [comment]
Added in latest commit. Now requires UdonToolkit
