### ISSUE TITLE
[Bug] Included Ender 3 blend file doesn't import to Unity

### ISSUE THREAD

**Issue by thetrueyoshifan** [Codel1417/VRC-Ender-3#2]
When importing the Unity Package into my project, the .blend file does not properly import, producing an empty object with no meshes, and leading to the printer being invisible
![Unity_yDY2cgLloy](https://user-images.githubusercontent.com/42860543/121975015-5016ac00-cd46-11eb-834c-16a061a86aa2.png)

**Comment by thetrueyoshifan** [comment]
Actually, this might be a Unity issue. I noticed that attempting to open the .blend file in Blender 2.79 causes a crash, as it's intended to be opened in a newer version (not your fault). Unity seems to like to use the first version of Blender it can find on the system, which in my case, is 2.79, and so the import fails because it cannot internally convert the .blend file to another format. A potential solution could be to have the prefab reference a .fbx file instead

**Comment by Codel1417** [comment]
fixed in 1.1
