### ISSUE TITLE
stops working when it raches 20000 mesh vertices/1000 trail size anyway to fix that?

### ISSUE THREAD

**Issue by CodySallot** [Codel1417/VRC-Ender-3#4]
![image_2021-08-26_195011](https://user-images.githubusercontent.com/19227091/131050256-890c83d7-d516-4aea-9f2b-769022cf4af3.png)

**Comment by Codel1417** [comment]
https://github.com/Codel1417/VRC-Ender-3/releases/tag/V1.2
