### ISSUE TITLE
[BUG] Interface freezes

### ISSUE THREAD

**Issue by nathanimall** [Codel1417/VRC-Ender-3#5]
Interface freeze after certain amount of time printing, most likely dependent on vertices.
Interface freeze after hitting cancel print.

**Comment by Codel1417** [comment]
i have a new version in progress that should fix cases of this. i hope to have it out tomorrow

**Comment by Codel1417** [comment]
I Pushed a new Update https://github.com/Codel1417/VRC-Ender-3/releases/tag/V1.2
