### ISSUE TITLE
Unity 2019.4.31f1 tons of U# compile errors

### ISSUE THREAD

**Issue by 4Bakers** [Codel1417/VRC-Ender-3#6]
![image](https://user-images.githubusercontent.com/50242229/163333619-8c5b3d64-a807-4e7f-b071-1f5448d70b57.png)
![image](https://user-images.githubusercontent.com/50242229/163333670-48064571-17e6-489d-97fb-34c31e242cdc.png)
I'm assuming it's not compatible with the latest version?

**Comment by Codel1417** [comment]
Those compile errors are from a different script.
