### ISSUE TITLE
Printer will print in 'sections', which will disappear before moving on to the next one

### ISSUE THREAD

**Issue by Furglitch** [Codel1417/VRC-Ender-3#7]
Not exactly sure how to explain any further but will give any additional information as necessary. Video attached.
Everything else about the printer works perfectly. 

https://user-images.githubusercontent.com/78628049/177216937-3897b2fc-d587-4260-8a36-0224336437ef.mp4

**Comment by Furglitch** [comment]
I guess I will add my gcode in case that's the issue
[maker.txt](https://github.com/Codel1417/VRC-Ender-3/files/9042108/maker.txt)

**Comment by Furglitch** [comment]
Issue also occurs when using CyanEmu to test world in unity

**Comment by Codel1417** [comment]
Im aware of this. Ive been working on a big update and this is fixed. Just waiting for a Udon bug to be fixed

**Comment by Codel1417** [comment]
This should be fixed now, Tested with both normal SDK3 and Creator Companion Sdks
